### ISSUE TITLE
Error while running the inference.

### ISSUE THREAD

**Issue by BakingBrains** [Sreyan88/Indic-ASR#1]
While running the inference, I am getting this error.

```
D:\pycharmprojects\Indic-ASR\venv\Scripts\python.exe D:/pycharmprojects/Indic-ASR/run_inference/transcription.py
2021-11-17 21:04:05 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "D:/pycharmprojects/Indic-ASR/run_inference/transcription.py", line 22, in <module>
    hypos = transcriber.transcribe(files)
  File "D:\pycharmprojects\Indic-ASR\run_inference\stt_2.py", line 312, in transcribe
    state=state,)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\checkpoint_utils.py", line 370, in load_model_ensemble
    state,
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\checkpoint_utils.py", line 465, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\tasks\audio_pretraining.py", line 198, in build_model
    model = super().build_model(model_cfg)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\tasks\fairseq_task.py", line 331, in build_model
    model = models.build_model(cfg, self)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\models\__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\models\wav2vec\wav2vec2_asr.py", line 181, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))
TypeError: object of type 'NoneType' has no len()
```

fairseq version is 0.10.2

**Comment by BakingBrains** [comment]
I managed resolve this error, Now I am getting model shape mismatch error.

```
D:\pycharmprojects\Indic-ASR\venv\Scripts\python.exe D:/pycharmprojects/Indic-ASR/run_inference/transcription.py
Traceback (most recent call last):
  File "D:/pycharmprojects/Indic-ASR/run_inference/transcription.py", line 22, in <module>
    hypos = transcriber.transcribe(files)
  File "D:\pycharmprojects\Indic-ASR\run_inference\stt_2.py", line 312, in transcribe
    state=state,)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\checkpoint_utils.py", line 269, in load_model_ensemble
    state,
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\checkpoint_utils.py", line 320, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
  File "d:\pycharmprojects\indic-asr\fairseq\fairseq\models\fairseq_model.py", line 115, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "D:\pycharmprojects\Indic-ASR\venv\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([183, 768]) from checkpoint, the shape in current model is torch.Size([318, 768]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([183]) from checkpoint, the shape in current model is torch.Size([318]).
```

Any suggestions?

Thanks

**Comment by BakingBrains** [comment]
Now I am getting this error which I am unable to resolve.

```
Traceback (most recent call last):
  File "/content/Indic-ASR/run_inference/transcription.py", line 22, in <module>
    lm_weight = 1.5, word_score = -1, beam_size = 50)
  File "/content/Indic-ASR/run_inference/stt_2.py", line 251, in __init__
    self.transcribe([sample_audio_path])
  File "/content/Indic-ASR/run_inference/stt_2.py", line 356, in transcribe
    generator = build_generator(args)
  File "/content/Indic-ASR/run_inference/stt_2.py", line 342, in build_generator
    from examples.speech_recognition.w2l_decoder import W2lKenLMDecoder
ModuleNotFoundError: No module named 'examples.speech_recognition'
```

**Comment by Sreyan88** [comment]
Hi @BakingBrains ,

Thank You for your interest in this repository. Can you please confirm if you have installed the fairseq library in the same fashion as suggested in the README of this repo?

'examples.speech_recognition' is a part of the fairseq lib.

Thank You

**Comment by BakingBrains** [comment]
Thanks for the quick reply.

Yes sir, I installed the fairseq library as suggested in your repo.
```
git clone https://github.com/pytorch/fairseq.git
cd fairseq
git checkout c8a0659be5cdc15caa102d5bbf72b872567c4859
pip install --editable ./
cd ..
```
Installation was successfull.

Now I am facing issue while installing wav2letter.

Followed the same step as mentioned in the repo:
```
git clone -b v0.2 https://github.com/facebookresearch/wav2letter.git
cd wav2letter/bindings/python
export KENLM_ROOT_DIR=path/to/libs/kenlm/ && pip install -e .
cd ../../..
```
Below is the error

```
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/content/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

what might be the issue?

Thank you

**Comment by Sreyan88** [comment]
Hi @BakingBrains ,

I would need to see the complete output of the logs to get a better understanding. Could you please provide that?

**Comment by BakingBrains** [comment]
This is the colab, [https://colab.research.google.com/drive/1pRA5dSfdiJaICuBeRklzvk-oCLaE9A4u?usp=sharing](https://colab.research.google.com/drive/1pRA5dSfdiJaICuBeRklzvk-oCLaE9A4u?usp=sharing
)

And reagrding the log, It is only showing the error which I sent above. Can you please tell which commit from the wav2letter should I install?

**Comment by Sreyan88** [comment]
Hi @BakingBrains ,

Can you please try this?

```
git clone -b v0.2 https://github.com/facebookresearch/wav2letter.git
cd wav2letter/bindings/python
export KENLM_ROOT_DIR=path/to/libs/kenlm/ && pip install -e .
cd ../../..
```

and these are the dependencies:

```
sudo apt-get update && sudo apt-get -y install apt-utils libpq-dev libsndfile-dev
sudo apt install libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev libeigen3-dev zlib1g-dev libbz2-dev liblzma-dev
sudo apt-get install libsndfile1-dev libopenblas-dev libfftw3-dev libgflags-dev libgoogle-glog-dev
```

**Comment by BakingBrains** [comment]
Thank you, I managed to resolve the issue

**Comment by BakingBrains** [comment]
I am still getting this error.

```
Traceback (most recent call last):
  File "/content/Indic-ASR/run_inference/transcription.py", line 22, in <module>
    lm_weight = 1.5, word_score = -1, beam_size = 50)
  File "/content/Indic-ASR/run_inference/stt_2.py", line 251, in __init__
    self.transcribe([sample_audio_path])
  File "/content/Indic-ASR/run_inference/stt_2.py", line 356, in transcribe
    generator = build_generator(args)
  File "/content/Indic-ASR/run_inference/stt_2.py", line 342, in build_generator
    from examples.speech_recognition.w2l_decoder import W2lKenLMDecoder
ModuleNotFoundError: No module named 'examples.speech_recognition'
```

After all the instrallation done, where do we need to place this indic-asr repository, inside libs folder of somewhere else?

**Comment by BakingBrains** [comment]
fairseq is installled successfully, but still the above error exits.

```
Cloning into 'fairseq'...
remote: Enumerating objects: 29868, done.
remote: Counting objects: 100% (1026/1026), done.
remote: Compressing objects: 100% (610/610), done.
remote: Total 29868 (delta 492), reused 812 (delta 397), pack-reused 28842
Receiving objects: 100% (29868/29868), 14.03 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (22167/22167), done.
Checking out files: 100% (1163/1163), done.
/content/self-supervised-speech-recognition/libs/fairseq
Note: checking out 'c8a0659be5cdc15caa102d5bbf72b872567c4859'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c8a0659b Stronger --checkpoint-activations test (#1505)
Obtaining file:///content/self-supervised-speech-recognition/libs/fairseq
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: hydra-core<1.1 in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (1.0.7)
Requirement already satisfied: torch in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (1.6.0+cu101)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (4.62.3)
Requirement already satisfied: sacrebleu>=1.4.12 in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (2.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (1.19.5)
Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (0.29.24)
Requirement already satisfied: omegaconf<2.1 in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (2.0.6)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (2019.12.20)
Requirement already satisfied: cffi in /usr/local/lib/python3.7/dist-packages (from fairseq==1.0.0a0+c8a0659) (1.15.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.7/dist-packages (from hydra-core<1.1->fairseq==1.0.0a0+c8a0659) (5.4.0)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /usr/local/lib/python3.7/dist-packages (from hydra-core<1.1->fairseq==1.0.0a0+c8a0659) (4.8)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from omegaconf<2.1->fairseq==1.0.0a0+c8a0659) (3.10.0.2)
Requirement already satisfied: PyYAML>=5.1.* in /usr/local/lib/python3.7/dist-packages (from omegaconf<2.1->fairseq==1.0.0a0+c8a0659) (6.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from sacrebleu>=1.4.12->fairseq==1.0.0a0+c8a0659) (0.4.4)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.7/dist-packages (from sacrebleu>=1.4.12->fairseq==1.0.0a0+c8a0659) (0.8.9)
Requirement already satisfied: portalocker in /usr/local/lib/python3.7/dist-packages (from sacrebleu>=1.4.12->fairseq==1.0.0a0+c8a0659) (2.3.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi->fairseq==1.0.0a0+c8a0659) (2.21)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources->hydra-core<1.1->fairseq==1.0.0a0+c8a0659) (3.6.0)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from torch->fairseq==1.0.0a0+c8a0659) (0.16.0)
Installing collected packages: fairseq
  Running setup.py develop for fairseq
Successfully installed fairseq-1.0.0a0+c8a0659
```

**Comment by Sreyan88** [comment]
Hi @BakingBrains ,

Did you manage to fix the error? Did it need any additional change? Would love to know!

**Comment by BakingBrains** [comment]
Actually i was using colab, so there was some issue related to fairseq path. What I did is after installing fairseq

```
! echo $PYTHONPATH

import os
os.environ['PYTHONPATH'] += ":/content/self-supervised-speech-recognition/libs/fairseq/"

! echo $PYTHONPATH
```

Did this in colab and everything worked well.
Thank you for the response.
